# Generated by Django 2.1 on 2018-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='preview_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
