# Generated by Django 2.1 on 2018-08-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0002_auto_20180823_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
